(executables
 (names qiskit mbqc unitary primitives verif)
 (modes exe)
 (libraries alcotest sQbricks)
 ;  (flags :standard -w -a)
 )

(rule
 (alias qiskit)
 (action
  (run ./qiskit.exe)))

(rule
 (alias mbqc)
 (action
  (run ./mbqc.exe)))

(rule
 (alias unitary)
 (action
  (run ./unitary.exe)))

(rule
 (alias primitives)
 (action
  (run ./primitives.exe)))

(rule
 (alias verif)
 (action
  (run ./verif.exe)))
